# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/nicksc1cc/inflexion-website.git
  branch: gh-pages
  message: 'Site updated: {{ now("YYYY-MM-DD HH:mm:ss") }}'